name: Telegram Pull Request Notifier
# on:
#   pull_request:
#     types: [opened, review_requested]
on:
  issue_comment:
    types:
      - created
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned]
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types:
      - created
  push:
    branches:
      - main

jobs:
  tg_post_job:
    runs-on: ubuntu-latest
    name: A job to post data in tg
    steps:
      - name: Send data
        uses: BorisTestov/tg_sender_action@latest
        env:
          TG_SENDER_TG_CHAT_ID: ${{ secrets.CHATID }}
          TG_SENDER_TG_BOT_TOKEN: ${{ secrets.BotToken }}
          TG_SENDER_PAYLOAD_MESSAGE: "🚀 Hello World!"


# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: send telegram message on push
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.BotToken }}
#           token: ${{ secrets.CHATID }}
#           message: |
#             ${{ github.actor }} created commit:
#             Commit message: ${{ github.event.commits[0].message }}
            
#             Repository: ${{ github.repository }}
            
#             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
# name: Notify Telegram
# on:
#   issue_comment:
#     types:
#       - created
#   issues:
#     types: [opened, edited, pinned, closed, reopened, assigned]
#   pull_request:
#     types: [opened, closed, edited, ready_for_review, review_requested, reopened]
#   pull_request_review_comment:
#     types:
#       - created
#   push:
#     branches:
#       - main

# jobs:
#  test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test
#         uses: georgepstaylor/telegram-github-notifier@v0.0.1
#         with:
#           telegram_bot_token: ${{ secrets.BotToken }}
#           telegram_chat_id: ${{ secrets.CHATID }}
#           gh_event: ${{ toJson(github.event) }}
#           gh_actor: ${{ github.actor }}
          
